default_language_version:
  python: python3.10
files: |
  (?x)^(
    ^check_raise_gen_return/|
    ^test/
  )
exclude: |
  (?x)^(
    ^check_raise_gen_return.egg-info/
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
    - id: check-toml
    - id: debug-statements
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: end-of-file-fixer
      exclude_types: [json]
    - id: check-merge-conflict
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
#      additional_dependencies: ['click<8.1']
      name: black (reformat python code)
      language_version: python3.10

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
    - id: pyupgrade
      args: [--py310-plus]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      name: isort (sort python imports)
      args: ["--profile=black", "--python-version=310", "--line-length=94", "--filter-files"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks: # run flake but dont stop on errors
    - id: flake8
      verbose: true
      entry: bash -c 'flake8 "$@" || true' --

  - repo: local
    hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest
      types: [python]
      language: system
      pass_filenames: false
      always_run: true
      stages: [push]

# https://mypy.readthedocs.io/en/stable/existing_code.html
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.931
#    hooks:
#    - id: mypy
#      args: [--no-strict-optional, --ignore-missing-imports]
#      files: ^server/
#      types: [python]
#      language: system
#      always_run: true
